version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medicalEquipmentDB

  spring-boot-app:
    build: ./MedicalEquipmentPlatform
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medicalEquipmentDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
  
  react-app: 
    build: ./react_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on: 
      - spring-boot-app